backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: ../../static/images/

logo_url: ../logo1.png

locale: 'sr'

collections:
#  - label: "Cenovnik"
#    name: "cena"
#    widget: "list"
#    folder: 'content/cenovnik'
#    preview: false
#    create: true
#    fields:
#      - { label: 'Usluga', name: 'title', widget: 'string' }
#      - label: 'Vrsta'
#        name: 'vrsta'
#        widget: 'list'
#        create: true
#        fields:
#          - { label: 'Vrsta usluge', name: 'vrstaUsluge', widget: 'string' }
#          - { label: 'Cena usluge', name: 'cenaUsluge', widget: 'string' }


  - label: "Objava"
    name: 'objava'
    folder: 'content/objava'
    preview: false
    create: true
    fields:
      - label: Obavestenje
        name: title
        widget: string
      - label: Objavi
        name: draft
        widget: boolean
        default: false
      - name: body
        label: Tekst
        widget: text




#
#  - label: "Efekti"
#    name: 'efekti'
#    folder: 'content/efekti'
#    preview: false
#    create: false
#    fields:
#      #      - { label: 'Tekst objave', name: 'title', widget: 'text' }
#      - { label: 'Efekt', name: 'title', widget: 'string' }
#      - { label: 'Ukljuci', name: 'draft', widget: 'boolean' }
